import 'package:flutter/material.dart';

class Am7 extends StatefulWidget { const Am7({super.key});

@override State<Am7> createState() => _Am7State(); }

class _Am7State extends State<Am7> { bool showMethods = false;

final List<Map<String, String>> methods = [ { 'no': '01', 'icon': 'engineering', 'title': 'Network Assessment & Planning', 'description': 'Analyze current infrastructure, capacity, and performance metrics to identify bottlenecks and plan network upgrades tailored for scalability and 5G-readiness.' }, { 'no': '02', 'icon': 'architecture', 'title': 'Security Framework Implementation', 'description': 'Design and implement security layers including DDoS protection, firewalls, and end-to-end encryption for data in transit and at rest.' }, { 'no': '03', 'icon': 'integration_instructions', 'title': 'Architecture Design', 'description': ' Craft high-availability, software-defined architectures using NFV/SDN, edge computing, and scalable core networks to support growing demand.' }, { 'no': '04', 'icon': 'rule_folder', 'title': 'Service Integration & Orchestration', 'description': 'Seamlessly integrate OSS/BSS systems, customer portals, and multi-vendor environments with intelligent orchestration and automation.' }, { 'no': '05', 'icon': 'rocket_launch', 'title': 'Testing & Performance Validation', 'description': 'Perform rigorous testing including throughput, QoS, latency analysis, and failover simulation to validate performance under peak loads.' }, { 'no': '06', 'icon': 'support_agent', 'title': 'Deployment & Rollout', 'description': 'Execute secure rollout of new services across regions with phased deployment, zero-downtime migrations, and customer communication strategies.' }, ];

@override Widget build(BuildContext context) { final screenWidth = MediaQuery.of(context).size.width; return Container( color: Colors.transparent, padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24), child: Column( crossAxisAlignment: CrossAxisAlignment.center, children: [ Center( child: ElevatedButton( onPressed: () { setState(() => showMethods = !showMethods); }, style: ElevatedButton.styleFrom( shape: RoundedRectangleBorder( borderRadius: BorderRadius.circular(30), ), backgroundColor: Colors.indigo, padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14), ), child: const Text( 'Our Telecom Development Process', style: TextStyle(fontSize: 16, color: Colors.white), ), ), ), const SizedBox(height: 24), if (showMethods) ...methods.map( (item) => Container( margin: const EdgeInsets.only(bottom: 16), padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20), decoration: BoxDecoration( color: Colors.white, borderRadius: BorderRadius.circular(20), boxShadow: [ BoxShadow( color: Colors.black12, blurRadius: 8, offset: const Offset(0, 4), ), ], ), child: Row( crossAxisAlignment: CrossAxisAlignment.start, children: [ Text( item['no']!, style: const TextStyle( fontWeight: FontWeight.bold, fontSize: 20, color: Colors.indigo), ), const SizedBox(width: 12), Icon( _getIcon(item['icon']!), size: 28, color: Colors.indigoAccent, ), const SizedBox(width: 12), Expanded( child: Column( crossAxisAlignment: CrossAxisAlignment.start, children: [ Text( item['title']!, style: const TextStyle( fontSize: 16, fontWeight: FontWeight.bold), ), const SizedBox(height: 4), Text( item['description']!, style: const TextStyle(fontSize: 14), ), ], ), ) ], ), ), ), ], ), ); }

IconData _getIcon(String iconName) { switch (iconName) { case 'engineering': return Icons.engineering; case 'architecture': return Icons.architecture; case 'integration_instructions': return Icons.integration_instructions; case 'rule_folder': return Icons.rule_folder; case 'rocket_launch': return Icons.rocket_launch; case 'support_agent': return Icons.support_agent; default: return Icons.device_hub; } } }
